
@BASE_URL = http://localhost:8000

@API_URL_V1 = {{BASE_URL}}/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55IjoiNjE1YTg5MThjYzFkYTMwNmU4MTgwNTY0IiwiZGV2aWNlSWQiOiJ0ZXN0LTEyMzQ1NiIsImRldmljZVVzZXJUeXBlIjoiRGVza3RvcEFwcCIsImludGVncmF0aW9uVHlwZSI6IldPQ09OTkVDVF9ERUZBVUxUIiwibG9jYXRpb24iOiI2NjQzNmNiMWYyNzM3ZGNlM2NkYzUzYjEiLCJpYXQiOjE3MjA3ODg3Mjd9.rw9Of-JUnvjea8lbCSlqVF2upuYF5-bvJPqpER30qiU
### status
GET {{API_URL_V1}}/healthchecker HTTP/1.1
